language: python
virtualenv:
  system_site_packages: true
python:
  - '2.7'
env:
  - DJANGO=1.11.11
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
before_script:
  - 'export PATH=$PATH:/usr/lib/chromium-browser/'
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
script:
  - behave
