# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='carshop',
            name='shopName',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
