# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 16:41
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_auto_20180319_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('kms', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='Color', max_length=30)),
                ('registrationYear', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarShop',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('inaugurationYear', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('shopName', models.CharField(max_length=30, null=True)),
                ('addr', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('modelName', models.CharField(max_length=30, null=True)),
                ('body', models.CharField(max_length=30, null=True)),
                ('fuelType', models.IntegerField(choices=[(1, 'Gasoline'), (2, 'Diesel'), (3, 'Electric'), (4, 'Hybrid')], default=1)),
                ('modelYear', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018)),
                ('maxTopSpeed', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)])),
                ('doors', models.IntegerField(choices=[(1, '3 Doors'), (2, '5 Doors')], default=2)),
                ('seats', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=5)),
            ],
        ),
        migrations.CreateModel(
            name='ModelReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('street', models.CharField(max_length=30, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1)),
                ('city', models.CharField(max_length=30, null=True)),
                ('postCode', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('phoneNumber', models.IntegerField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Car')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField(default=0)),
                ('info', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Person')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.CarShop')),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='restaurantreview',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantReview',
        ),
        migrations.AddField(
            model_name='sell',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Seller'),
        ),
        migrations.AddField(
            model_name='customer',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Person'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.CarShop'),
        ),
        migrations.AddField(
            model_name='car',
            name='carShop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.CarShop'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Model'),
        ),
    ]
