# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 19:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0002_auto_20180319_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kms', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('color', models.IntegerField(blank=True, null=True)),
                ('registrationYear', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarShop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('modelYear', models.IntegerField(blank=True, null=True)),
                ('shopName', models.TextField(blank=True, null=True)),
                ('addr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('modelName', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('fuelType', models.TextField(blank=True, null=True)),
                ('modelYear', models.IntegerField(blank=True, null=True)),
                ('maxTopSpeed', models.TextField(blank=True, null=True)),
                ('doors', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('street', models.TextField(blank=True, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('postCode', models.IntegerField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('phoneNumber', models.IntegerField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Car')),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('info', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Person')),
                ('shop', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.CarShop')),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='restaurantreview',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantReview',
        ),
        migrations.AddField(
            model_name='sell',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Seller'),
        ),
        migrations.AddField(
            model_name='customer',
            name='info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Person'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.CarShop'),
        ),
        migrations.AddField(
            model_name='car',
            name='carShop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.CarShop'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributors.Model'),
        ),
    ]
