# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-18 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_auto_20180518_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
