# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 09:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0003_auto_20180415_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carshop',
            name='modelYear',
        ),
        migrations.AddField(
            model_name='carshop',
            name='inaugurationYear',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018),
        ),
        migrations.AlterField(
            model_name='carshop',
            name='addr',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='carshop',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carshop',
            name='shopName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='model',
            name='body',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='model',
            name='doors',
            field=models.IntegerField(choices=[(1, '3 Doors'), (2, '5 Doors')], default=2),
        ),
        migrations.AlterField(
            model_name='model',
            name='fuelType',
            field=models.IntegerField(choices=[(1, 'Gasoline'), (2, 'Diesel'), (3, 'Electric'), (4, 'Hybrid')]),
        ),
        migrations.AlterField(
            model_name='model',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='model',
            name='maxTopSpeed',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='model',
            name='modelName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='model',
            name='modelYear',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018),
        ),
        migrations.AlterField(
            model_name='model',
            name='seats',
            field=models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.TextField(),
        ),
    ]
