# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 09:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0004_auto_20180416_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='Color', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='kms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='registrationYear',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carshop',
            name='addr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='carshop',
            name='shopName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='body',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='fuelType',
            field=models.IntegerField(choices=[(1, 'Gasoline'), (2, 'Diesel'), (3, 'Electric'), (4, 'Hybrid')], default=1),
        ),
        migrations.AlterField(
            model_name='model',
            name='maxTopSpeed',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='model',
            name='modelName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='postCode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
