# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributors', '0005_auto_20180416_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=70, null=True),
        ),
    ]
